# Generated by Django 2.1.5 on 2024-03-24 18:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flat', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='rooms',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='post',
            name='value',
            field=models.CharField(choices=[('USD', 'USD'), ('BYN', 'BYN'), ('EUR', 'EUR'), ('RUB', 'RUB')], default='USD', max_length=50),
        ),
    ]
