# Generated by Django 5.0.3 on 2024-03-16 18:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flat', '0003_myfiles_remove_post_image'),
    ]

    operations = [
        migrations.DeleteModel(
            name='MyFiles',
        ),
        migrations.AddField(
            model_name='post',
            name='file',
            field=models.FileField(default=1, upload_to='upldfile/'),
            preserve_default=False,
        ),
    ]
