# Generated by Django 5.0.3 on 2024-03-16 19:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flat', '0004_delete_myfiles_post_file'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='file',
        ),
        migrations.AddField(
            model_name='post',
            name='image',
            field=models.ImageField(default=1, upload_to=''),
            preserve_default=False,
        ),
    ]
