# Generated by Django 5.0.3 on 2024-03-16 19:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flat', '0005_remove_post_file_post_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='image',
            field=models.ImageField(upload_to='images'),
        ),
    ]
