# Generated by Django 5.0.3 on 2024-03-16 20:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flat', '0006_alter_post_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='all_square',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='post',
            name='flor',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='post',
            name='kitchen_square',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='post',
            name='living_square',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
