# Generated by Django 5.0.3 on 2024-03-17 18:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_remove_customer_email_remove_customer_phone_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customer',
            name='last_login',
        ),
        migrations.RemoveField(
            model_name='seller',
            name='last_login',
        ),
    ]
